# Generated by Django 5.1.4 on 2025-01-12 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='ps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_services', to='main.services'),
        ),
    ]
